name: Update sudare

on:
  repository_dispatch:
    types: [update-sudare]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Update formula
        run: |
          echo "${{ github.event.client_payload }}"
      - name: action-ejs
        uses: jaywcjlove/action-ejs@main
        with:
          template-file: Formula/sudare.rb.ejs
          output: Formula/sudare.rb
          vars: ${{ toJSON(github.event.client_payload) }}
      - run: |
          cat Formula/sudare.rb
